### ISSUE TITLE
Créer une image docker plutôt que tout réinstaller à chaque run

### ISSUE THREAD

**Issue by ColinMaudry** [139bercy/decp-rama#11]
Aujourd'hui, [le script CircleCI](https://github.com/etalab/decp-rama/blob/master/.circleci/config.yml) réinstalle à chaque fois les différentes dépendances nécessaires au traitement des données.

Il serait plus économe en temps, et donc en énergie, de constituer une image Docker qui aurait par avance toutes les dépendances nécessaires, de la publier, et de l'utiliser dans ce script.

**Comment by ColinMaudry** [comment]
@abulte Quand t'as un moment :slightly_smiling_face:

**Comment by ColinMaudry** [comment]
Idéalement je veux bien que tu travailles sur une branche `feature/docker`.

**Comment by ColinMaudry** [comment]
Done.

**Comment by ColinMaudry** [comment]
Hello @abulte !

J'ai ajouté des trucs dans le Dockerfile, mais j'ai peur de casser la prod si je publie l'image sans tester. Et je ne sais pas trop comment tester.

https://github.com/etalab/decp-rama/commit/360857f0378648535dd520f14d341a765d3d4e49#diff-3254677a7917c6c01f55212f86c57fbf

Ça se passe sur la branche `feature/ocds`.

Pourrais-tu te charger de tester et publier la nouvelle image en évitant de casser la prod (obviously) ? Merci !

**Comment by ColinMaudry** [comment]
Cette config est inspirée de la doc présente ici : https://flatten-tool.readthedocs.io/en/latest/getting-started/

**Comment by abulte** [comment]
J'ai fait des remarques là-bas https://github.com/etalab/decp-rama/commit/360857f0378648535dd520f14d341a765d3d4e49#diff-3254677a7917c6c01f55212f86c57fbf

Je te propose de faire les modifs et quand ce sera bon je publierai une image sur Dockerhub ailleurs que `etalab/decp-rama` et on pourra la tester sans casser la prod en la référençant ici https://github.com/etalab/decp-rama/blob/master/.circleci/config.yml#L5. Tu peux d'ailleurs le faire avec ton propre compte Dockerhub en utilisant https://github.com/etalab/decp-rama/blob/master/publish-docker.sh en local après avoir remplacer `etalab` par ton handle Dockerhub.

(Je reviens de congés début août).
