### ISSUE TITLE
Circle jobs tend to timeout when data grows a lot

### ISSUE THREAD

**Issue by ColinMaudry** [139bercy/decp-rama#35]
The growth of the total number of marchés increases the length of the substraction of new marchés from the total: https://github.com/etalab/decp-rama/blob/master/scripts/get_new_data.sh#L74

We can either:

- extend timeout in circle CI
- find another way of extracting the new marchés
- move the processing to a server that doesn't timeout

**Comment by strainel** [comment]
L'extraction des nouveaux marchés a été revue et le temps de traitement de cette partie a été fortement diminué. Je clos cette demande.
