### ISSUE TITLE
Glossaire: Peut-on voir les participants a l'appel d'offre?

### ISSUE THREAD

**Issue by ogierpaul** [139bercy/decp-rama#51]
Bonjour,
Je souhaite savoir si dans le dataset, il est possible de voir toutes les entités ayant candidatés / fait des offres pour le marché en question?
Je vous remercie,
Paul

**Comment by ColinMaudry** [comment]
Bonjour,

[L'arrêté](https://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=3D2929632230F708292116DE624BFC97.tplgfr27s_3?idArticle=JORFARTI000038318690&cidTexte=JORFTEXT000038318675&dateTexte=29990101&categorieLien=id) qui définit la liste des champs exigés n'inclut pas la liste des soumissionnaires. Cette information ne figure donc pas dans [les données](https://www.data.gouv.fr/fr/datasets/5cd57bf68b4c4179299eb0e9/) publiées via ces scripts.

N'hésitez pas à revenir vers nous si vous avez d'autres questions.

**Comment by ogierpaul** [comment]
Bonjour,
Je vous remercie pour les deux liens tres clairs.
Vous pouvez fermer cette issue.

**Comment by ColinMaudry** [comment]
J'ai corrigé le lien vers l'arrêté, car il n'affichait que l'article 8.
