### ISSUE TITLE
Conversion du JSON agrégé au format OCDS JSON : HS

### ISSUE THREAD

**Issue by strainel** [139bercy/decp-rama#63]
```
Nombre de marchés dans le fichier des nouveaux marchés : 210

## Conversion du JSON agrégé en XML...
-rw-r--r-- 1 root root 265M Apr 16 09:14 xml/decp.xml

## Conversion du JSON du jour en XML...
-rw-r--r-- 1 root root 234K Apr 16 09:14 decp_2021-04-16.xml

## Conversion du JSON agrégé au format OCDS JSON...
Error: writing output failed: Cannot allocate memory

Exited with code exit status 2
CircleCI received exit code 2
```

et j'ai testé en local, le script fonctionne bien. mystère. @edaubert

**Comment by edaubert** [comment]
Souci de mémoire ou du disque.

je regarde

**Comment by edaubert** [comment]
À première vue, ce n'est pas lié à la modification apportée hier.

C'est au moment de l'aggrégation de l'ensemble des traitements (après que chaque source a été traité).

Il doit monter en mémoire trop d'information au vue de la limite mémoire imposé par CircleCI.

Je cherche une solution concernant jq pour qu'il soit plus performant en mémoire

**Comment by edaubert** [comment]
https://github.com/139bercy/decp-rama/pull/64

J'ai un fix qui devrait normalement passer.

Je peux éventuellement modifier la CI pour qu'il s'exécute depuis cette MR afin de valider complètement.

**Comment by strainel** [comment]
est-ce que tu as comparé le fichier `decp.ocds` publié et celui nouvellement généré

**Comment by edaubert** [comment]
non j'ai comparé celui que l'on génère en local mais qui ne se génère pas  dans la CI avec celui que j'ai généré avec ma nouvelle version.

Le souci c'est de généré ce fichier `decp.ocds.json` dans la CI donc je suis partie de l'hypothèse qu'il était bon avec le code existant et je l'ai généré sur mon ordinateur.

J'ai ensuite travaillé sur ma version pour trouver une optimisation de la mémoire.

Comme j'ai le même résultat avec ma version de code qu'avec celle qui ne passe pas en CI (à cause de la mémoire) j'en conclus que je n'ai rien cassé au niveau de la génération du fichier.

Si il y a une autre manière de faire je suis preneur car même si je suis plutôt convaincu de mon test, vu que je ne connais pas vraiment le projet, je peux faire une erreur...

**Comment by strainel** [comment]
Parfait ; allons y alors.

**Comment by edaubert** [comment]
Il semble que le fix ne fonctionne pas correctement.

je regarde

**Comment by strainel** [comment]
pas de nouvelles @edaubert  ? ce matin, je fais le traitement localement.

**Comment by edaubert** [comment]
Je tente des choses mais pour le moment je n'y arrive pas.

Et comme je ne reproduis pas en local...

De plus je ne comprends pas l'erreur.
Je poursuis mes investigations

**Comment by edaubert** [comment]
J'ai trouvé le fix, il est dans la MR.

Mais j'ai fait un changement en plus concernant la CI afin de pouvoir tester mon souci.
De ce fait, github marque la CI en cours d'exécution alors qu'elle est terminée.

On peut corriger cela dans la configuration du projet mais je n'ai pas les droits pour m'en occuper.

**Comment by strainel** [comment]
Merci @edaubert ; que faut il changer dans la conf CI ?

**Comment by edaubert** [comment]
Finalement j'ai commenté les changements concernant la configuration a changé.

Je regarderai plus en détails et ferai une autre MR.
