### ISSUE TITLE
Optimisation du diff entre marchés déjà connus et nouveaux marchés

### ISSUE THREAD

**Issue by edaubert** [139bercy/decp-rama#68]
Actuellement après 5h nous avons un timeout qui se déclenche ne permettant pas de terminer le processus de traitement de données.

C'est la différence entre marchés déjà connus et nouveaux marchés qui est longue.

Il faut donc optimiser le script correspondant c'est-à-dire `scripts/get_new_data.sh`

**Comment by edaubert** [comment]
@strainel @ColinMaudry 

Je suis en train de faire des tests pour faire cette optimisation mais je me rends compte que la diff entre `decp_previous.json` et `json/decp.json` me donne beaucoup de marchés qui n'existe plus.

Par exemple aujourd'hui, j'ai 9910 marchés qui n'existent plus et 3174 nouveaux marchés.
Un marché qui n'existe plus c'est un marché présent dans le decp_previous mais pas présent dans le nouveaux fichiers.

Est-ce normal ?
Il est possible que ma comparaison soit fausse c'est pour cela que je demande.
En effet d'après l'exécution de samedi, seulement 1887 marchés sont nouveaux.
Je suis en train de relancer le process actuel pour pouvoir comparer les fichiers mais bon j'ai plus de 5h d'attente...

Pour information je passe à moins d'une demi-heure de traitement contrairement au 5h du timeout.
Il me reste sûrement quelques corrections mais j'espère être clairement en dessous de l'heure de traitement.

**Comment by strainel** [comment]
Pour moi, le `diff` ne fonctionne pas très bien. Il ne renvoie jamais le nombre attendu de marchés...

**Comment by edaubert** [comment]
D'après l'exécution de la branche master en local chez moi, j'ai bien 3174 nouveaux marchés.

Le diff ne peut pas fonctionner sur l'ensemble du fichier mais il peut fonctionner sur les uids seulement.
C'est le mode de fonctionnement que j'ai implémenté dans la MR.

J'attends le résultat final pour comparer précisément les fichiers de résultat

**Comment by ColinMaudry** [comment]
Donc le mystère c'est les 9910 marchés supprimés. Il peut y avoir des marchés supprimés dans les sources (heureusement on les a en stock dans les fichiers journaliers !), mais 9910 en quelques jours ça me parait beaucoup. La balance a toujours été positive (https://139bercy.github.io/decp-monitoring/).

**Comment by ColinMaudry** [comment]
Je vois sur https://139bercy.github.io/decp-monitoring/ que la courbe de marches-publics.info part en flèche. J'ai lancé le traitement de master en local pour avoir les uid de ces marchés supprimés. Peut-être que leur `.source` nous apprendra quelque chose.

**Comment by ColinMaudry** [comment]
Bon je ne pourrai pas beaucoup vous aider dans l'immédiat, chez moi j'ai résultats très bizarres :

- `data.gouv.fr_aife contient 80 marchés`
- et maximilien fail

```
Conversion (atexo-maximilien)...
atexo-maximilien.xml...
Traceback (most recent call last):
  File "/home/colin/.local/bin/xml2json", line 8, in <module>
    sys.exit(main())
  File "/home/colin/.local/lib/python3.8/site-packages/xmljson/__main__.py", line 39, in main
    json.dump(dialect.data(parse(in_file).getroot()), out_file, indent=2)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1880, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1900, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1795, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1201, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "/home/colin/git/decp-rama/sources/atexo-maximilien/<stdin>", line 155439
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 155439, column 41
## Empaquetage (atexo-maximilien)...

atexo-maximilien contient 0 marchés

```
Je vais aller voir si le problème de maximilien est du côté de mon jeu de données. Si maximilien fail aussi chez vous, ça peut être la source des 9000+ marchés manquants.
