### ISSUE TITLE
Incomple OCDS JSON file

### ISSUE THREAD

**Issue by yolile** [139bercy/decp-rama#76]
https://static.data.gouv.fr/resources/donnees-essentielles-de-la-commande-publique-fichiers-consolides/20210611-052223/decp.ocds.json used to work well, but now it is an incomplete/truncated JSON file, for checking you can:

`curl https://static.data.gouv.fr/resources/donnees-essentielles-de-la-commande-publique-fichiers-consolides/20210611-052223/decp.ocds.json | tail -c 100`

and see that the file ends unexpectedly with:

`21","legalName":"Etablissement public territorial Plaine Commune "}},{"name":"SOUFFLET VIGNE","id":"`

Maybe the system ran out of memory when running: https://github.com/139bercy/decp-rama/blob/80ce53afca91346ebdceef5ebb363788de8b12c1/scripts/makeOCDS_json.sh#L13?

**Comment by ColinMaudry** [comment]
Not sure what has been done (I don't work on it anymore), but it's fixed :)
